In [2]:
import xyz # random word (module which is not available in python )

ModuleNotFoundError: No module named 'xyz'

In [ ]:
# if you got modulenotfounderror while working on import 
# ModuleNotFoundError:

# 1. Spelling mistake
# 2. case sensistive 
# 3. Re install your module

In [ ]:
# go to pypi website ( www.pypi.org )
# search for numpy 
# get pip install numpy code 
# execute it by adding ! before pip

# In our machine numpy is already available so it says requirement already satisfied

In [3]:
!pip install numpy # it will open anaconda prompt and it will execute pip install command 

In [10]:
list1 = [1,2,3,4,5]
[i**2 for i in list1]

[1, 4, 9, 16, 25]

In [9]:
list1 = [1,2,3,4,5]
rs = []
for i in list1:
    rs.append(i**2)
print(rs)

[1, 4, 9, 16, 25]


In [4]:
import numpy # as numpy module is a default library which is in anaconda ,its not throwing an error

#### Creat an array

In [6]:
ar1 = numpy.array([1,2,3,4])
ar1

array([1, 2, 3, 4])

In [7]:
type(ar1) # n dimensional array

numpy.ndarray

In [8]:
ar1**2

array([ 1,  4,  9, 16])

In [11]:
import numpy as np

In [12]:
np.array([1,2,3])

array([1, 2, 3])

In [13]:
np.zeros([3,2]) # shape --> 3,2 --> 3 rows and 2 columns 
# create an array fill with zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
np.random.random([3,2])
# creates a random array between 0 and 1

array([[0.27462815, 0.67808112],
       [0.88442454, 0.78202368],
       [0.48161151, 0.47094772]])