In [1]:
import numpy as np

In [2]:
np.array(['a','b','c'])

array(['a', 'b', 'c'], dtype='<U1')

In [3]:
np.array([True,False,True])

array([ True, False,  True])

#### Array Initialization

In [4]:
np.full([3,4], 10) # 2 parameters ( shape, value)
# is to create an array with 3 rows and 4 cols and fill the array with value 10

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [5]:
np.full([2,2], 'a') 

array([['a', 'a'],
       ['a', 'a']], dtype='<U1')

In [6]:
range(0,5)

range(0, 5)

In [9]:
for i in range(0,5):
    print(i,end = '')

01234

In [10]:
list(range(0,4))

[0, 1, 2, 3]

In [11]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [12]:
np.arange(0,10,2) # start , end-1, step-1

array([0, 2, 4, 6, 8])

In [13]:
np.arange(1,10,3) # start , end-1, step-1

array([1, 4, 7])

In [14]:
np.linspace(0,10,6) # start ,end(including), count of values to generate
# from 0 including 10 ,will generate 6 numbers which has equal difference

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [15]:
np.linspace(0,10,8) 
# from 0 till 10 generate 8 numbers which should have equal difference

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [ ]:
# Attribute Error
# 1. spelling 
# 2. case sensitive 
# 3. function doesnt exisit

#### Array Inspection

In [24]:
ar1 = np.arange(1,25)
ar1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [25]:
ar1.size # no.of elements

24

In [27]:
type(ar1)

numpy.ndarray

In [28]:
ar1.ndim #no.of dimensions

1

In [ ]:
# if shape needs to be altered then size of array should match with no.of rows* columns
24 = 1*24
2*12
3*8
4*6

In [30]:
ar2 =  ar1.reshape(6,4)
ar2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [31]:
ar2.ndim

2

In [32]:
ar1.reshape(5,5)
# 5*5!= 24

ValueError: cannot reshape array of size 24 into shape (5,5)

In [33]:
ar1.reshape(3,3)
# 3*3!= 24

ValueError: cannot reshape array of size 24 into shape (3,3)

In [42]:
ar2= np.arange(1,25).reshape(6,4)
ar2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [40]:
ar3= np.arange(1,25).reshape(3,2,4)
ar3.ndim

3

In [41]:
ar3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [45]:
ar2.dtype

dtype('int32')

In [46]:
ar2.shape

(6, 4)

#### Array Mathematics

In [47]:
ar1 = np.array([[10,20],[30,40]])
ar1

array([[10, 20],
       [30, 40]])

In [48]:
np.sum(ar1) # sum all the numbers

100

In [49]:
np.sum(ar1, axis = 0) # axis = 0 ---> perform summation across rows

array([40, 60])

In [50]:
np.sum(ar1, axis = 1) # axis = 1 ---> perform summation across columns

array([30, 70])

In [51]:
print(np.subtract(10,20))
print(np.multiply(10,20))
print(np.divide(10,20))

-10
200
0.5


In [52]:
print(np.log(10))
print(np.exp(10))
print(np.sqrt(10))
print(np.sin(10))

2.302585092994046
22026.465794806718
3.1622776601683795
-0.5440211108893698


In [53]:
np.mean([10,20,30,40,50]) # average = sum/total --> (10+20+30+40+50)/5

30.0

In [54]:
np.min([10,20,30,40,50]) # average = sum/total --> (10+20+30+40+50)/5

10

In [55]:
np.max([10,20,30,40,50]) # average = sum/total --> (10+20+30+40+50)/5

50

#### Indexing

In [56]:
list1 = ['a','b','c','d','e']
list1[1]

'b'

In [58]:
list1[1:3] #b,c

['b', 'c']

In [ ]:
# index will always start with zero
# end value is not included 

In [61]:
ar1 = np.arange(11,20)
ar1

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [62]:
ar1[2]

13

In [63]:
ar1[2:5]

array([13, 14, 15])

In [64]:
ar1 = np.arange(1,25).reshape(6,4)
ar1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [65]:
ar1[2:4,1:3]

array([[10, 11],
       [14, 15]])

In [66]:
ar1[2:6,0:4]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [67]:
# no starting or ending value mentioned --> automatically picks 0 for start and whatever is available as last value

In [69]:
ar1[2:,0:4] # 2: --> as no end value mentioned python will execute till last

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [70]:
ar1[2:,0:]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [71]:
ar1[2:] # it will extract only rows , including every columns

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [73]:
ar1[3:5,2:4]

array([[15, 16],
       [19, 20]])

In [72]:
ar1[:, 1:3] # extract all rows and 1,2 columns

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])