#### Array manipulation

In [1]:
import numpy as np

In [2]:
ar1 = np.array([[10,20],[30,40]])
ar2 = np.array([[50,60],[70,80]])

In [3]:
ar2

array([[50, 60],
       [70, 80]])

In [5]:
np.concatenate([ar1,ar2], axis = 0) # axis = 0 --> rows 4 rows and 2 columns

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [9]:
np.vstack([ar1,ar2])

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [7]:
np.row_stack([ar1,ar2])

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [6]:
np.concatenate([ar1,ar2], axis = 1) # axis = 1 --> columns --> 2 rows and 4 columns

array([[10, 20, 50, 60],
       [30, 40, 70, 80]])

In [10]:
np.column_stack([ar1,ar2])

array([[10, 20, 50, 60],
       [30, 40, 70, 80]])

In [12]:
np.hstack([ar1,ar2])

array([[10, 20, 50, 60],
       [30, 40, 70, 80]])

In [13]:
ar3 = np.column_stack([ar1,ar2,ar1])
ar3

array([[10, 20, 50, 60, 10, 20],
       [30, 40, 70, 80, 30, 40]])

In [14]:
np.hsplit(ar3,3) # divide this array into 3 equal parts

[array([[10, 20],
        [30, 40]]),
 array([[50, 60],
        [70, 80]]),
 array([[10, 20],
        [30, 40]])]